version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - tvbackend
      
  web:
    image: python:3.9
    working_dir: /app
    volumes:
      - ./saveload_backend:/app
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=''
    ports:
      - "8000:8000"
    command: bash -c "pip install -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    networks:
      - tvbackend

networks:
  tvbackend:
    driver: bridge